/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ItemUpdateManyWithoutOrdersInput } from "./ItemUpdateManyWithoutOrdersInput";
import { ValidateNested, IsOptional, IsNumber, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { OrderUpdateManyWithoutOrdersInput } from "./OrderUpdateManyWithoutOrdersInput";
import { OrderWhereUniqueInput } from "./OrderWhereUniqueInput";
import { EnumOrderStatus } from "./EnumOrderStatus";
@InputType()
class OrderUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ItemUpdateManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => ItemUpdateManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => ItemUpdateManyWithoutOrdersInput, {
    nullable: true,
  })
  items?: ItemUpdateManyWithoutOrdersInput;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutOrdersInput, {
    nullable: true,
  })
  orders?: OrderUpdateManyWithoutOrdersInput;

  @ApiProperty({
    required: false,
    type: () => OrderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OrderWhereUniqueInput)
  @IsOptional()
  @Field(() => OrderWhereUniqueInput, {
    nullable: true,
  })
  owner?: OrderWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumOrderStatus,
  })
  @IsEnum(EnumOrderStatus)
  @IsOptional()
  @Field(() => EnumOrderStatus, {
    nullable: true,
  })
  status?: "Accepted" | "InProrgres" | "Done" | null;
}
export { OrderUpdateInput };
